id: start
task: Ant-v3
screen_height: 100
screen_width: 100
train:
  epochs: 4
  seed: 1234
  num_workers: 2
  worker_steps: 128
  num_mini_batch: 4
  objective:
    name: PPO
    gamma: 0.99
    lambda: 0.95
